# Use Playwright GUI
[confirm('Open Playwright in browser?')]
ui:
	npx playwright test --ui

# This list of test commands
help:
	just --list

# Headless test
headless *args="":
	npx playwright test {{args}}

# Pre-deployment test
for-deploy:
	just headless --project=webkit
