default:
	just --list

# Proxy to deploy `justfile`
deploy *args="":
	cd deploy && just {{args}}

# Start PHP's built-in webserver
dev port='4000':
	cd ../module/Esunview/webroot && PHP_CLI_SERVER_WORKERS=2 php -S localhost:{{port}} index.php
