services:
  lipupini:
    build:
      context: ../../../..
      dockerfile: ./system/deploy/docker/php-builtin/Dockerfile
      tags:
        - "dcc2/php-builtin-lipupini:latest"
    ports:
      - "8080:8080" # HTTP
    restart: unless-stopped
    volumes:
      - ../../../collection:/app/collection:rw
