# This list of Docker commands
help:
	just --list

# Generate a Docker image from `system/deploy/docker`
build type='frankenphp':
	docker-compose --file ./{{type}}/docker-compose.yml build
	# docker build --tag esunview/esunview-{{type}}:latest --file .{{type}}/Dockerfile .

# Run Docker container from generated Docker image
up type='frankenphp':
	docker-compose --file ./{{type}}/docker-compose.yml up
	# docker run -it --rm --name esunview/esunview-{{type}}:latest esunview-{{type}}
